// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadText(arg1) {
  return window['go']['main']['App']['ReadText'](arg1);
}

export function SaveText(arg1, arg2) {
  return window['go']['main']['App']['SaveText'](arg1, arg2);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function ServerURL() {
  return window['go']['main']['App']['ServerURL']();
}

export function Translate(arg1) {
  return window['go']['main']['App']['Translate'](arg1);
}

export function Txt2Docx(arg1, arg2) {
  return window['go']['main']['App']['Txt2Docx'](arg1, arg2);
}
