// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1:string,arg2:Array<string>):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ReadText(arg1:string):Promise<string>;

export function SaveText(arg1:string,arg2:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function ServerURL():Promise<string>;

export function Translate(arg1:string):Promise<string>;

export function Txt2Docx(arg1:string,arg2:string):Promise<string>;
